name: .Net Core

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishReadyToRun=true
    - name: Upload OneCom demo artifacts
      uses: actions/upload-artifact@v2
      with:
        name: One.comDemo
        path: /home/runner/work/onecomdemo/onecomdemo/WebApp2/bin/Release/net5.0/linux-x64/publish/